# Generated by Django 5.0.1 on 2024-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor_id',
            field=models.ManyToManyField(related_name='measurements', to='measurement.sensor'),
        ),
    ]
